#
# Prefixed commands
#

# Create a new nested tmux (Ctrl + z, Ctrl + s)
# bind C-t new-window "$TPM_PLUGIN_DIR/new-tmux.tmux" \; \
#          rename-window '' \; \
#          command-prompt -I "#W" "rename-window -- '%%'"

# Adapted From:
# Answer: https://unix.stackexchange.com/a/269542/270053
# User: https://unix.stackexchange.com/users/84561/tagwint
# Create a new nested tmux (Ctrl + z, Ctrl + s)
# bind C-t new-window "$TPM_PLUGIN_DIR/new-tmux.tmux" \; \
#          command-prompt "rename-window -- '%%'"

# Create a new nested tmux (Ctrl + z, Ctrl + t)
bind C-t command-prompt { new-window "$TPM_PLUGIN_DIR/new-tmux.tmux" \; rename-window -- '%%' }

# Create a new nested smug (Ctrl + z, Ctrl + s)
bind C-s command-prompt { new-window "$TPM_PLUGIN_DIR/new-basis.tmux" 'attach' '%%' \; rename-window -- '%%' }

# Rename current window (Ctrl + z, A)
# bind A  rename-window '' \; \
#         command-prompt -I "#W" "rename-window -- '%%'"

# Rename current window (Ctrl + z, A)
bind A command-prompt "rename-window -- '%%'"

# Enable search mode
bind -T copy-mode -n / command-prompt -i -I "#{pane_search_string}" -p "(search down)" "send -X search-forward-incremental \"%%%\""

#
# Non-prefixed commands
#

# bind -n C-t new-window
# bind -n C-v paste-buffer

# Go to next window (Alt + Right)
bind -n M-right next
bind -n M-l     next

# Go to previous window (Alt + Left)
bind -n M-left  prev
bind -n M-h     prev

# Handler for becoming active (Alt + F12, don't use directly)
bind -n M-F12 run-shell "$TPM_PLUGIN_DIR/move-up.tmux"

# Handler for closed window: enable outer terminal
set-hook -g client-detached { run-shell "tmux -L $TMUX_PARENT run-shell '$TPM_PLUGIN_DIR/active-row.tmux'" }
set-hook -g session-closed { run-shell "tmux -L $TMUX_PARENT run-shell '$TPM_PLUGIN_DIR/active-row.tmux'" }

source-file $HOME/.config/tmux/keybindings.conf
